production:
  adapter: mysql2
  database: aws_playground_production
  username: root
  password: password
  pool: 5
  timeout: 5000
  socket: /var/run/mysqld/mysqld.sock

development:
  adapter: mysql2
  database: aws_playground_development
  username: root
  password:
  pool: 5
  timeout: 5000
